
message("Numerics showing 0 is false")
set(MYVAR1 1)
set(MYVAR2 0)
if(MYVAR2)
    message("In if: value was " ${MYVAR2})
elseif(MYVAR1)
    message(" in else if: value was " ${MYVAR1})
endif()

message("Strings are more complicated")
set(FOO "T")
set(bar ${FOO})
message("FOO = " ${FOO} " BAR = " ${bar})
set(result "NONE")
if(bar)
    set(result "TRUE: BAR does not match the requirement for false")
else()

    set(result "FALSE: BAR matches conditions for false")
endif()
message("\nWith BAR refs, result is " ${result})

if(${bar})
    set (result "True: Bar evaluates to a Truethy value")
else()
    set(result "False: Bar doesn't evaluate to a Truethy value")
endif()
message("With Quoted refs, result is " ${result})
message ("\n")